version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: jwt-implementation-express-docker
    command: --default-authentication-plugin=mysql_native_password 
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ../backend
    container_name: jwt-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=jwt-implementation-express-docker
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - db

volumes:
  mysql_data: